/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.74
 * Generated at: 2023-06-24 03:25:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.client;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class introduce_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/Esclipse%20EE/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/BestPriceWeb/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098685890000L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1592930816000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("<!-- Start header section -->\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./header/mainHeader.jsp", out, true);
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<section id=\"aa-catg-head-banner\">\n");
      out.write("	<img\n");
      out.write("		src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/view/client/assets/images/blog-banner.jpg\"\n");
      out.write("		alt=\"banner sản phẩm\" style=\"width: 100%\">\n");
      out.write("	<div class=\"aa-catg-head-banner-area\">\n");
      out.write("		<div class=\"container\">\n");
      out.write("			<div class=\"aa-catg-head-banner-content\">\n");
      out.write("				<h2>Giới thiệu</h2>\n");
      out.write("				<ol class=\"breadcrumb\">\n");
      out.write("					<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">Trang\n");
      out.write("							chủ</a></li>\n");
      out.write("					<li style=\"color: #fff\">Giới thiệu</li>\n");
      out.write("				</ol>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("</section>\n");
      out.write("<section id=\"aa-product-category\">\n");
      out.write("	<div class=\"container\">\n");
      out.write("		<div class=\"row\">\n");
      out.write("			<div>\n");
      out.write("				<h1 style=\"text-align: center; color: red;\">Best Price Việt Nam</h1>\n");
      out.write("				<p>\n");
      out.write("					Chúng tôi hi vọng tất cả người tiêu dùng Việt nam sẽ được sử dụng\n");
      out.write("					những sản phẩm uy tín, giá tốt và chất lượng nhất tại\n");
      out.write("					trang web bán hàng trực tuyến <strong>Best Price</strong>.Với sứ mệnh trở thành một trong\n");
      out.write("					những nhà cung cấp các sản phẩm tiện ích, cũng như thực phẩm uy tín hàng đầu tại Việt Nam đưa đến người tiêu dùng loại sản phẩm giá tốt nhất của các vùng miền trên toàn quốc với mục đích là <strong>“Mang\n");
      out.write("						thiên nhiên về với căn nhà của bạn”</strong>. Với sự hợp tác độc quyền với các thương hiệu hàng đầu thế giới. Chúng tôi tự tin mang lại các sản phẩm tốt với giá cả cạnh tranh nhưng chất lượng thì vẫn không thay đổi so với thị trường\n");
      out.write("				</p>\n");
      out.write("				<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/introduce_thuc_pham_sach.png\"\n");
      out.write("					alt=\"Thực phẩm sạch\" /> <br /> <br>\n");
      out.write("				<p>\n");
      out.write("					Với triết lý trong kinh doanh là tuân thủ và đảm bảo được chất\n");
      out.write("					lượng tươi ngon nhất, nguồn gốc xuất xứ về sản phẩm rõ ràng.Chúng\n");
      out.write("					tôi cam kết không sử dụng chất bảo quản nào bị Bộ Y Tế cấm không\n");
      out.write("					được sử dụng và cam kết với quý khách hàng về toàn bộ những sản\n");
      out.write("					phẩm được phân phối qua hệ thống phân phối <strong>Best Price</strong> đảm bảo an toàn nhất.\n");
      out.write("				</p>\n");
      out.write("				<p>Với cam kết chỉ phân phối những hàng hóa được cung cấp từ\n");
      out.write("					những nhà sản xuất có uy tín và đã được cơ quan y tế có thẩm quyền\n");
      out.write("					cấp chứng nhận và đảm bảo vệ sinh an toàn thực phẩm có đủ quyền\n");
      out.write("					cung cấp thực phẩm sạch, các loại nông sản là các đặc sản từ mọi\n");
      out.write("					miền trên toàn quốc, các thực phẩm sử dụng hàng ngày như các thực\n");
      out.write("					phẩm được đóng gói, thực phẩm được chế biến sẵn, rau củ quả, các\n");
      out.write("					loại gạo vùng miền và các loại phụ gia về thực phẩm như các loại\n");
      out.write("					gia vị dùng trong việc chế biến món ăn hàng ngày,...</p>\n");
      out.write("				<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/banner-product.jpg\"\n");
      out.write("					alt=\"Thực phẩm sạch\" width=\"1160\" height=\"600\" /> <br /> <br>\n");
      out.write("				<strong>Dưới đây, chúng tôi xin điểm qua những mặt hàng của\n");
      out.write("					Best Price</strong><br />\n");
      out.write("				<p>\n");
      out.write("					<strong>Rau củ sạch Đà Lạt, an toàn có nguồn gốc rõ ràng:\n");
      out.write("					</strong> Với những loại rau củ là những loại đặc sản tại các vùng miền <strong>Nông\n");
      out.write("						Sản 24h</strong> là địa chỉ uy tín cung cấp cho bạn các loại sản phẩm chất\n");
      out.write("					lượng từ các loại rau củ sạch Đà Lạt được nhiều người dân ủng hộ\n");
      out.write("					trong suốt khoảng thời gian qua.Hệ thống vận hành của chúng tôi\n");
      out.write("					được thực hiện theo dây chuyền đảm bảo rằng các bạn sẽ nhận được\n");
      out.write("					thực phẩm tươi nhất với thời gian vận chuyển ngắn nhất đáp ứng được\n");
      out.write("					độ tươi ngon đảm bảo vệ sinh, an toàn và ngon miệng.\n");
      out.write("				</p>\n");
      out.write("				<p>\n");
      out.write("					<strong>Hoa quả sạch, xuất xứ rõ ràng: </strong> Với mục tiêu trở\n");
      out.write("					thành một thương hiệu được khách hàng tin tưởng và coi như một địa\n");
      out.write("					chỉ mua sắm tin cậy đối với các loại trái cây nhập khẩu và trái cây\n");
      out.write("					Việt Nam có chất lượng cao cho gia đình, <strong>Best Price</strong> đang trở nên hoàn thiện hơn để đem đến cho khách hàng không\n");
      out.write("					chỉ những sản phẩm Trái cây nhập khẩu, trái cây Việt Nam chất lượng\n");
      out.write("					hàng đầu trên thị trường mà kèm theo đó là những dịch vụ tiện ích\n");
      out.write("					thân thiện khác.\n");
      out.write("				</p>\n");
      out.write("				<p>\n");
      out.write("					<strong>Các trang thiết bị đồ gia dụng gia đình</strong> Chúng tôi cung cấp các sản phẩm đồ gia dụng thông minh phục vụ thị trường. Hứa hẹn sẽ tiên phong đi đầu trong công cuộc tạo các giá trị tích cực trong cuộc sống và trong thế hệ 4.0\n");
      out.write("				</p>\n");
      out.write("				<p>\n");
      out.write("					<strong>Điện thoại, đồ công nghệ</strong> là những sản phẩm độc quyền được phân phối từ samsung hay apple. Chúng tôi nắm trong tay các sản phẩm bản quyền sắp và sẽ ra mắt trên thị trường. Đảm bảo khách hàng sẽ có trên tay các sản phẩm sớm nhất với giá cả ưu đãi nhất. Nhưng không vì thế mà giảm uy tín và chất lượng. Chúng tôi chú trọng đến sự thoải mái của người dùng với chính sách bảo hàng từ 1 đến 4 năm.\n");
      out.write("				</p>\n");
      out.write("				<br />\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<!--  footer-->\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./footer/footer.jsp", out, true);
      out.write("\n");
      out.write("<!-- end footer-->\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /view/client/introduce.jsp(3,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/view/client/assets");
      // /view/client/introduce.jsp(3,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setVar("url");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }
}
