/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.74
 * Generated at: 2023-06-24 03:24:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/Esclipse%20EE/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/BestPriceWeb/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098685890000L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1592930816000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

  response.setHeader("Cache-control", "no-cache, no-store, must-revalidate");
  response.setHeader("Pragma" , "no-cache");
  response.setHeader("Expires" , "0");
  
  
  if (session.getAttribute("admin-username") == null){
	  response.sendRedirect(request.getContextPath() + "/admin/login"); 
  }
  
      out.write("\n");
      out.write("<!-- Start header section -->\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./header/header.jsp", out, true);
      out.write("\n");
      out.write("<div class=\"content-wrapper\">\n");
      out.write("	<div class=\"container-fluid\">\n");
      out.write("		<div class=\"card mt-3\">\n");
      out.write("			<div class=\"card-content\">\n");
      out.write("				<div class=\"row row-group m-0\">\n");
      out.write("					<div class=\"col-12 col-lg-6 col-xl-3 border-light\">\n");
      out.write("						<div class=\"card-body\">\n");
      out.write("							<h5 class=\"text-white mb-0\">\n");
      out.write("								3 <span class=\"float-right\"><i\n");
      out.write("									class=\"fa fa-shopping-cart\"></i></span>\n");
      out.write("							</h5>\n");
      out.write("							<div class=\"progress my-3\" style=\"height: 3px;\">\n");
      out.write("								<div class=\"progress-bar\" style=\"width: 55%\"></div>\n");
      out.write("							</div>\n");
      out.write("							<p class=\"mb-0 text-white small-font\">\n");
      out.write("								Đơn hàng (theo tuần)<span class=\"float-right\">+4.2% <i\n");
      out.write("									class=\"zmdi zmdi-long-arrow-up\"></i></span>\n");
      out.write("							</p>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"col-12 col-lg-6 col-xl-3 border-light\">\n");
      out.write("						<div class=\"card-body\">\n");
      out.write("							<h5 class=\"text-white mb-0\">\n");
      out.write("								230.000 <span class=\"float-right\">VNĐ</span>\n");
      out.write("							</h5>\n");
      out.write("							<div class=\"progress my-3\" style=\"height: 3px;\">\n");
      out.write("								<div class=\"progress-bar\" style=\"width: 55%\"></div>\n");
      out.write("							</div>\n");
      out.write("							<p class=\"mb-0 text-white small-font\">\n");
      out.write("								Lợi nhuận (theo tuần)<span class=\"float-right\">+1.2% <i\n");
      out.write("									class=\"zmdi zmdi-long-arrow-up\"></i></span>\n");
      out.write("							</p>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"col-12 col-lg-6 col-xl-3 border-light\">\n");
      out.write("						<div class=\"card-body\">\n");
      out.write("							<h5 class=\"text-white mb-0\">\n");
      out.write("								25 <span class=\"float-right\"><i class=\"fa fa-eye\"></i></span>\n");
      out.write("							</h5>\n");
      out.write("							<div class=\"progress my-3\" style=\"height: 3px;\">\n");
      out.write("								<div class=\"progress-bar\" style=\"width: 55%\"></div>\n");
      out.write("							</div>\n");
      out.write("							<p class=\"mb-0 text-white small-font\">\n");
      out.write("								Ghé trang (theo tuần)<span class=\"float-right\">+5.2% <i\n");
      out.write("									class=\"zmdi zmdi-long-arrow-up\"></i></span>\n");
      out.write("							</p>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"col-12 col-lg-6 col-xl-3 border-light\">\n");
      out.write("						<div class=\"card-body\">\n");
      out.write("							<h5 class=\"text-white mb-0\">\n");
      out.write("								3 <span class=\"float-right\"><i class=\"fa fa-envira\"></i></span>\n");
      out.write("							</h5>\n");
      out.write("							<div class=\"progress my-3\" style=\"height: 3px;\">\n");
      out.write("								<div class=\"progress-bar\" style=\"width: 55%\"></div>\n");
      out.write("							</div>\n");
      out.write("							<p class=\"mb-0 text-white small-font\">\n");
      out.write("								Bán ra (theo tuần)<span class=\"float-right\">+2.2% <i\n");
      out.write("									class=\"zmdi zmdi-long-arrow-up\"></i></span>\n");
      out.write("							</p>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"row\">\n");
      out.write("			<div class=\"col-12 col-lg-4 col-xl-4\">\n");
      out.write("				<div class=\"card\">\n");
      out.write("					<div class=\"card-header\">Danh mục bán chạy</div>\n");
      out.write("					<div class=\"card-body\">\n");
      out.write("						<div class=\"chart-container-2\">\n");
      out.write("							<canvas id=\"chart2\"></canvas>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"table-responsive\">\n");
      out.write("						<table class=\"table align-items-center\">\n");
      out.write("							<tbody>\n");
      out.write("								<tr>\n");
      out.write("									<td><i class=\"fa fa-circle text-white mr-2\"></i>Rau sạch</td>\n");
      out.write("									<td>58.000 VNĐ</td>\n");
      out.write("									<td>+55%</td>\n");
      out.write("								</tr>\n");
      out.write("								<tr>\n");
      out.write("									<td><i class=\"fa fa-circle text-light-1 mr-2\"></i>Củ quả</td>\n");
      out.write("									<td>110.000 VNĐ</td>\n");
      out.write("									<td>+25%</td>\n");
      out.write("								</tr>\n");
      out.write("								<tr>\n");
      out.write("									<td><i class=\"fa fa-circle text-light-2 mr-2\"></i>Hạt</td>\n");
      out.write("									<td>215.500 VNĐ</td>\n");
      out.write("									<td>+15%</td>\n");
      out.write("								</tr>\n");
      out.write("								<tr>\n");
      out.write("									<td><i class=\"fa fa-circle text-light-3 mr-2\"></i>Mật ong</td>\n");
      out.write("									<td>310.000 VNĐ</td>\n");
      out.write("									<td>+5%</td>\n");
      out.write("								</tr>\n");
      out.write("							</tbody>\n");
      out.write("						</table>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("</div>\n");
      out.write("<a href=\"javaScript:void();\" class=\"back-to-top\"><i\n");
      out.write("	class=\"fa fa-angle-double-up\"></i> </a>\n");
      out.write("<div class=\"right-sidebar\">\n");
      out.write("	<div class=\"switcher-icon\">\n");
      out.write("		<i class=\"zmdi zmdi-settings zmdi-hc-spin\"></i>\n");
      out.write("	</div>\n");
      out.write("	<div class=\"right-sidebar-content\">\n");
      out.write("		<p class=\"mb-0\">Màu nền admin</p>\n");
      out.write("		<hr>\n");
      out.write("		<ul class=\"switcher\">\n");
      out.write("			<li id=\"theme1\"></li>\n");
      out.write("			<li id=\"theme2\"></li>\n");
      out.write("			<li id=\"theme3\"></li>\n");
      out.write("			<li id=\"theme4\"></li>\n");
      out.write("			<li id=\"theme5\"></li>\n");
      out.write("			<li id=\"theme6\"></li>\n");
      out.write("		</ul>\n");
      out.write("		<p class=\"mb-0\">Màu nền gradient</p>\n");
      out.write("		<hr>\n");
      out.write("		<ul class=\"switcher\">\n");
      out.write("			<li id=\"theme7\"></li>\n");
      out.write("			<li id=\"theme8\"></li>\n");
      out.write("			<li id=\"theme9\"></li>\n");
      out.write("			<li id=\"theme10\"></li>\n");
      out.write("			<li id=\"theme11\"></li>\n");
      out.write("			<li id=\"theme12\"></li>\n");
      out.write("			<li id=\"theme13\"></li>\n");
      out.write("			<li id=\"theme14\"></li>\n");
      out.write("			<li id=\"theme15\"></li>\n");
      out.write("		</ul>\n");
      out.write("	</div>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./footer/footer.jsp", out, true);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
